### PR TITLE
Lesson One, the NDK implements

### PR DESCRIPTION
**Pull request by biezhihua**
Hi,learnopengles:

I tried to implement the NDK version of lesson 1, it is possible to submit to your repository?
I will to implement more lesson.

Thanks.

@learnopengles

### CODE REVIEW

**Comment by learnopengles** [comment]
Hi, thank you for the PR and sorry about the delay -- notifications appear buggered on my side. I'll check this out soon and get back to you.

**Comment by learnopengles** [comment]
Interesting -- thanks for the PR! Would it be possible to put the implementation under its own folder; i.e. android/cpp ? That way the base lessons would stay in Java and follow the website, and we can have multiple implementations in parallel without having to add too much complexity to the code itself.

**Comment by biezhihua** [comment]
Ok!  I will to change the PR as soon and notice to you.

@learnopengles

**Comment by biezhihua** [comment]
@learnopengles 

Hi,I moved all the cpp files to the src/main/java/com/learnopengles/cpp directory.

Is that ok ?

**Comment by biezhihua** [comment]
@learnopengles 

Hi,I moved all the implementation files to the src/main/java/com/learnopengles/cpp directory.

Is that ok ?

**Comment by biezhihua** [comment]
@learnopengles

**Comment by learnopengles** [comment]
@biezhihua I would move it a level further out; i.e. to have this structure

/android/AndroidOpenGLESLessons
/android/AndroidOpenGLESLessonsCpp <-- The CPP commits would go here.

It's OK to duplicate the textures, etc... so that the project can be self-contained.

There's also another PR that wants to add Kotlin support and it can start to get complicated if we have all of these changes to the same app.

**Comment by biezhihua** [comment]
@learnopengles 

I moved all the implementation files to the .../android/AndroidOpenGLESLessonsCpp directory.

If the PR be approved. I will commit other implementation as soon.

**Comment by learnopengles** [comment]
Hi @biezhihua, sorry, to clarify I mean that they should be in a separate project from the root. So in this repository there is a /android/AndroidOpenGLESLessons folder, and then the CPP lessons should go in a /android/AndroidOpenGLESLessonsCpp folder. So the folder structure would look like this, relative to the root:

/android/AndroidOpenGLESLessonsCpp <-- CPP lessons in here.

Otherwise, we are getting there. :)

**Comment by biezhihua** [comment]
@learnopengles 
Oh , I understand!

**Comment by biezhihua** [comment]
Hi , I have moved the implementation to the android/AndroidOpenGLESLessonsCpp according to your requirements.

I don't know if it's okay?

@learnopengles

**Comment by learnopengles** [comment]
Hi, I didn't try to compile it yet but at a first glance it looks good now. Thanks! :)

**Comment by biezhihua** [comment]
Why not merge the Pull Request? 
I plan to submit some other lessons.

Thanks! :)

@learnopengles

**Comment by learnopengles** [comment]
@biezhihua OK, done! I didn't yet have time to check everything yet but I committed the PR so as not to leave you blocked.

**Pull request merged**
